import React from 'react';
import {
  DashboardOutlined,
  TeamOutlined,
  SafetyOutlined,
  BankOutlined,
  AppstoreOutlined,
  HddOutlined,
  ThunderboltOutlined,
  AlertOutlined,
  CloudUploadOutlined,
  LineChartOutlined,
  VideoCameraOutlined,
  FileSearchOutlined,
  SettingOutlined,
  BellOutlined,
  ShareAltOutlined,
  FundOutlined,
  ProjectOutlined,
  GroupOutlined,
  TagOutlined,
  AimOutlined,
  UsbOutlined,
  ExportOutlined,
  FileTextOutlined,
  MessageOutlined,
  MonitorOutlined,
  KeyOutlined,
  BookOutlined,
  ReconciliationOutlined,
  LockOutlined,
  SecurityScanOutlined,
  CloudSyncOutlined,
  ApiOutlined,
  ScheduleOutlined,
  SendOutlined,
  ControlOutlined,
  DatabaseOutlined,
  ToolOutlined,
  MenuOutlined,
  FolderOutlined,
  HomeOutlined,
  UserOutlined,
  DesktopOutlined,
} from '@ant-design/icons';

const iconMap: Record<string, React.ReactNode> = {
  DashboardOutlined: <DashboardOutlined />,
  TeamOutlined: <TeamOutlined />,
  SafetyOutlined: <SafetyOutlined />,
  BankOutlined: <BankOutlined />,
  AppstoreOutlined: <AppstoreOutlined />,
  HddOutlined: <HddOutlined />,
  ThunderboltOutlined: <ThunderboltOutlined />,
  AlertOutlined: <AlertOutlined />,
  CloudUploadOutlined: <CloudUploadOutlined />,
  LineChartOutlined: <LineChartOutlined />,
  VideoCameraOutlined: <VideoCameraOutlined />,
  FileSearchOutlined: <FileSearchOutlined />,
  SettingOutlined: <SettingOutlined />,
  BellOutlined: <BellOutlined />,
  ShareAltOutlined: <ShareAltOutlined />,
  FundOutlined: <FundOutlined />,
  ProjectOutlined: <ProjectOutlined />,
  GroupOutlined: <GroupOutlined />,
  TagOutlined: <TagOutlined />,
  AimOutlined: <AimOutlined />,
  UsbOutlined: <UsbOutlined />,
  ExportOutlined: <ExportOutlined />,
  FileTextOutlined: <FileTextOutlined />,
  MessageOutlined: <MessageOutlined />,
  MonitorOutlined: <MonitorOutlined />,
  KeyOutlined: <KeyOutlined />,
  BookOutlined: <BookOutlined />,
  ReconciliationOutlined: <ReconciliationOutlined />,
  LockOutlined: <LockOutlined />,
  SecurityScanOutlined: <SecurityScanOutlined />,
  CloudSyncOutlined: <CloudSyncOutlined />,
  ApiOutlined: <ApiOutlined />,
  ScheduleOutlined: <ScheduleOutlined />,
  SendOutlined: <SendOutlined />,
  ControlOutlined: <ControlOutlined />,
  DatabaseOutlined: <DatabaseOutlined />,
  ToolOutlined: <ToolOutlined />,
  MenuOutlined: <MenuOutlined />,
  FolderOutlined: <FolderOutlined />,
  HomeOutlined: <HomeOutlined />,
  UserOutlined: <UserOutlined />,
  DesktopOutlined: <DesktopOutlined />,
};

export function getIcon(name: string | null | undefined): React.ReactNode {
  if (!name) return undefined;
  return iconMap[name] || undefined;
}

export default iconMap;
