-- =============================================================
-- V3: (已迁移) 通知中心表已移至 firefly-support V2__init_notification_center.sql
-- 如果已有 flyway_rule_history 记录，请运行: flyway repair
-- =============================================================
-- no-op
