-- =============================================================
-- V5: (已迁移) 消息模板表已移至 firefly-support V2__init_notification_center.sql
-- 如果已有 flyway_rule_history 记录，请运行: flyway repair
-- =============================================================
-- no-op
