export const ALARM_TEXT = {
  ruleMenu: '告警规则',
  recordMenu: '告警处理',
  ruleTitle: '告警规则',
  ruleDescription: '面向规则维护人员，负责定义规则组、触发条件、级别块和启停状态。',
  recordTitle: '告警处理',
  recordDescription: '面向值班和运维人员，负责确认、处理和关闭已触发的告警记录。',
  ruleName: '规则名称',
  scope: '适用范围',
  project: '所属项目',
  product: '适用产品',
  device: '指定设备',
  metric: '指标/属性',
  conditionList: '触发条件列表',
  conditionItemTitle: '条件',
  conditionLevel: '条件级别',
  addCondition: '新增条件',
  removeCondition: '删除条件',
  conditionCountSuffix: '条条件',
  primaryLevel: '规则主级别',
  primaryLevelDescription: '系统会按所有规则组中的最高严重级别自动归纳为：',
  multipleConditionHint:
    '先新增一个级别块，再选择该块的告警级别和触发语义，最后在块内维护条件。这样更接近现场告警升级思路。',
  customExpressionMetricHint: '自定义表达式无需选择指标',
  triggerType: '触发方式',
  triggerMode: '触发语义',
  triggerModeRequired: '请选择触发语义',
  triggerModePlaceholder: '请选择触发语义',
  triggerModeHint: '建议优先使用“全部满足”或“任意满足”；只有明确需要统计命中数量时再选择“至少 N 条满足”。',
  triggerModeDescription: '当前触发语义',
  matchCount: '满足条数',
  matchCountRequired: '请填写至少满足的条件条数',
  matchCountPlaceholder: '例如：2',
  preview: '规则预览',
  ruleGroupList: '告警级别块',
  ruleGroupTitle: '级别块',
  ruleGroupLevel: '告警级别',
  addRuleGroup: '新增级别块',
  removeRuleGroup: '删除级别块',
  ruleGroupPreview: '级别块预览',
  aggregateType: '统计口径',
  operator: '比较符',
  thresholdValue: '触发阈值',
  windowSize: '统计窗口',
  windowUnit: '时间单位',
  compareTarget: '对标方式',
  changeMode: '变化口径',
  changeDirection: '变化方向',
  consecutiveCount: '连续次数',
  customExpression: '自定义表达式',
  conditionTypeSummary: '支持阈值、同比/环比、连续触发、累计聚合和自定义表达式。',
  conditionTypeDescription:
    '优先选择项目、产品和物模型属性，再按级别块维护触发语义与条件；系统会自动生成结构化规则。',
  propertyHint: '选择产品后会自动加载物模型属性；如果暂无可选属性，可手工补充指标标识。',
  scopeHint: '建议至少选择产品，需要精确到单台设备时再继续选择设备。',
  level: '级别',
  condition: '触发条件',
  status: '状态',
  createdAt: '创建时间',
  action: '操作',
  description: '规则说明',
  levelPlaceholder: '请选择告警级别',
  searchRule: '搜索规则名称',
  searchRecord: '搜索告警标题',
  processStatus: '处理状态',
  triggerValue: '触发值',
  processRemark: '处理备注',
  title: '告警标题',
  close: '关闭',
  confirm: '确认',
  process: '处理',
  edit: '编辑',
  remove: '删除',
  createRule: '新建规则',
  createRuleTitle: '新建告警规则',
  editRuleTitle: '编辑告警规则',
  processTitle: '处理告警',
  totalRules: '规则总数',
  enabledRules: '已启用',
  disabledRules: '已停用',
  triggered: '待确认',
  confirmed: '已确认',
  processed: '已处理',
  closed: '已关闭',
  enabled: '启用',
  disabled: '停用',
  badge: '告警处理',
  countSuffix: '条',
  triggerTime: '触发时间',
  createRuleSuccess: '告警规则创建成功',
  createRuleError: '创建告警规则失败',
  updateRuleSuccess: '告警规则更新成功',
  updateRuleError: '更新告警规则失败',
  loadRuleError: '加载告警规则失败',
  deleteRuleTitle: '确认删除告警规则',
  deleteRuleSuccess: '告警规则已删除',
  deleteRuleError: '删除告警规则失败',
  deleteRuleMessagePrefix: '删除后不可恢复，确认删除“',
  deleteRuleMessageSuffix: '”吗？',
  loadScopeError: '加载项目/产品/设备选项失败',
  loadThingModelError: '加载产品物模型失败',
  loadRecordError: '加载告警记录失败',
  confirmSuccess: '告警已确认',
  confirmError: '确认告警失败',
  processSuccess: '告警已处理',
  processError: '处理告警失败',
  closeSuccess: '告警已关闭',
  closeError: '关闭告警失败',
  ruleNameRequired: '请输入规则名称',
  ruleNamePlaceholder: '例如：高温多条件告警',
  descriptionPlaceholder: '补充适用范围、触发背景或值班说明',
  projectPlaceholder: '可按项目范围限定规则',
  productPlaceholder: '请选择产品',
  devicePlaceholder: '可选，用于限定到单台设备',
  metricPlaceholder: '请选择物模型属性或输入指标标识',
  metricRequired: '请选择指标或填写指标标识',
  levelRequired: '请选择告警级别',
  conditionRequired: '请选择触发方式',
  thresholdPlaceholder: '例如：80',
  windowSizePlaceholder: '例如：1',
  consecutiveCountPlaceholder: '例如：3',
  customExprPlaceholder: '例如：payload.temperature > 50 && payload.humidity > 80',
  customExprRequired: '请输入自定义表达式',
  processRemarkPlaceholder: '请输入处理说明、工单号或值班记录',
  emptyScope: '全部范围',
  noMetricOptions: '暂无物模型属性',
  setupGuideTitle: '配置步骤',
  setupGuideDescription: '建议按“基本信息 -> 适用范围 -> 级别块策略”顺序配置，页面会实时汇总主级别和规则预览。',
  setupGuideBasic: '步骤 1 填基本信息',
  setupGuideBasicDesc: '先定义规则名称和适用背景，方便后续搜索、值班交接和规则巡检。',
  setupGuideScope: '步骤 2 定范围',
  setupGuideScopeDesc: '优先选产品，再按需细化到项目或单台设备，减少指标手输。',
  setupGuideBlocks: '步骤 3 配级别块',
  setupGuideBlocksDesc: '每个级别块先选级别和触发语义，再补条件，最后由系统自动汇总规则主级别。',
  configuredGroupCount: '已配置级别块',
  configuredConditionCount: '已配置条件数',
  basicCardTitle: '基本信息',
  scopeCardTitle: '适用范围与主级别',
  stepChooseLevel: '步骤 1 选择告警级别',
  stepChooseTrigger: '步骤 2 选择触发语义',
  stepReviewStrategy: '步骤 3 明确触发策略',
  stepConfigureConditions: '步骤 4 配置条件',
  levelStepHint: '先确定这是紧急、告警还是通知级别，再决定块内条件怎么组合。',
  strategyStepHint: '这里决定该级别块是“满足全部条件”才触发，还是用命中数量控制。',
  groupConditionHint: '同一个级别块里的条件共同服务于这一档告警等级，建议只放语义相关的一组条件。',
  metricSelectRecommended: '建议先选择产品',
  metricSelectRecommendedDesc: '选择产品后可直接从物模型属性中选指标，配置会更直观，也更不容易填错。',
  conditionParameterTitle: '条件参数',
  conditionHintThreshold: '适合“温度 > 80”这类直接阈值告警。',
  conditionHintCompare: '适合“当前比上一周期上涨 20%”这类趋势型告警。',
  conditionHintContinuous: '适合“连续多次命中阈值”后再触发，降低抖动误报。',
  conditionHintAccumulate: '适合统计窗口内求和、计数、累计值超限的场景。',
  conditionHintCustom: '仅在标准条件无法覆盖时使用，表达式会按结构化规则保存。',
} as const;

export const ALARM_LEVEL_LABELS: Record<string, string> = {
  CRITICAL: '紧急',
  WARNING: '告警',
  INFO: '通知',
};

export const ALARM_STATUS_LABELS: Record<string, string> = {
  TRIGGERED: ALARM_TEXT.triggered,
  CONFIRMED: ALARM_TEXT.confirmed,
  PROCESSED: ALARM_TEXT.processed,
  CLOSED: ALARM_TEXT.closed,
};
