export const ALARM_TEXT = {
  ruleMenu: '告警规则',
  recordMenu: '告警处理',
  recipientGroupMenu: '告警接收组',
  ruleTitle: '告警规则',
  ruleDescription:
    '面向规则维护人员，统一维护告警等级块、触发条件、通知方式和接收对象，确保告警触发后可以直接分发到值班人。',
  recordTitle: '告警处理',
  recordDescription: '面向值班和运维人员，负责确认、处理和关闭已经触发的告警记录。',
  recipientGroupTitle: '告警接收组',
  recipientGroupDescription:
    '将常用接收人整理成组，告警规则可直接按组编排，同时也支持在规则里补充指定人员。',
  ruleName: '规则名称',
  scope: '适用范围',
  project: '所属项目',
  product: '适用产品',
  device: '指定设备',
  metric: '指标属性',
  conditionList: '触发条件列表',
  conditionItemTitle: '条件',
  conditionLevel: '条件级别',
  addCondition: '新增条件',
  removeCondition: '删除条件',
  conditionCountSuffix: '个条件',
  primaryLevel: '规则主级别',
  primaryLevelDescription: '系统会按所有告警等级块中的最高严重级别自动归并为：',
  multipleConditionHint:
    '先新增一个告警等级块，再选择该块的告警级别和触发语义，最后在块内维护具体条件。这样更贴近现场告警分级策略。',
  customExpressionMetricHint: '自定义表达式无需选择指标',
  triggerType: '触发方式',
  triggerMode: '触发语义',
  triggerModeRequired: '请选择触发语义',
  triggerModePlaceholder: '请选择触发语义',
  triggerModeHint: '建议优先使用“全部满足”或“任意满足”；只有需要统计命中数量时，再选择“至少 N 条满足”。',
  triggerModeDescription: '当前触发语义',
  matchCount: '满足条数',
  matchCountRequired: '请填写至少满足的条件条数',
  matchCountPlaceholder: '例如：2',
  preview: '规则预览',
  ruleGroupList: '告警等级块',
  ruleGroupTitle: '等级块',
  ruleGroupLevel: '告警级别',
  addRuleGroup: '新增等级块',
  removeRuleGroup: '删除等级块',
  ruleGroupPreview: '等级块预览',
  aggregateType: '统计口径',
  operator: '比较符',
  thresholdValue: '触发阈值',
  windowSize: '统计窗口',
  windowUnit: '时间单位',
  compareTarget: '对标方式',
  changeMode: '变化口径',
  changeDirection: '变化方向',
  consecutiveCount: '连续次数',
  customExpression: '自定义表达式',
  conditionTypeSummary: '支持阈值、同环比、连续触发、累计聚合和自定义表达式。',
  conditionTypeDescription:
    '优先选择项目、产品和物模型属性，再按等级块维护触发语义与条件；系统会自动生成结构化规则。',
  propertyHint: '选择产品后会自动加载物模型属性；如当前还未维护物模型属性，可临时手动补充指标标识。',
  scopeHint: '建议至少选择产品，需要精确到单台设备时再继续限定设备。',
  level: '级别',
  condition: '触发条件',
  status: '状态',
  createdAt: '创建时间',
  updatedAt: '更新时间',
  action: '操作',
  description: '规则说明',
  levelPlaceholder: '请选择告警级别',
  searchRule: '搜索规则名称',
  searchRecord: '搜索告警标题',
  processStatus: '处理状态',
  triggerValue: '触发值',
  processRemark: '处理备注',
  title: '告警标题',
  close: '关闭',
  confirm: '确认',
  process: '处理',
  edit: '编辑',
  remove: '删除',
  createRule: '新建规则',
  createRuleTitle: '新建告警规则',
  editRuleTitle: '编辑告警规则',
  processTitle: '处理告警',
  totalRules: '规则总数',
  enabledRules: '已启用',
  disabledRules: '已停用',
  triggered: '待确认',
  confirmed: '已确认',
  processed: '已处理',
  closed: '已关闭',
  enabled: '启用',
  disabled: '停用',
  badge: '告警处理',
  countSuffix: '条',
  triggerTime: '触发时间',
  createRuleSuccess: '告警规则创建成功',
  createRuleError: '创建告警规则失败',
  updateRuleSuccess: '告警规则更新成功',
  updateRuleError: '更新告警规则失败',
  loadRuleError: '加载告警规则失败',
  deleteRuleTitle: '确认删除告警规则',
  deleteRuleSuccess: '告警规则已删除',
  deleteRuleError: '删除告警规则失败',
  deleteRuleMessagePrefix: '删除后不可恢复，确认删除“',
  deleteRuleMessageSuffix: '”吗？',
  loadScopeError: '加载项目、产品或设备选项失败',
  loadThingModelError: '加载产品物模型失败',
  loadRecordError: '加载告警记录失败',
  loadNotifyOptionsError: '加载通知方式或接收人选项失败',
  confirmSuccess: '告警已确认',
  confirmError: '确认告警失败',
  processSuccess: '告警已处理',
  processError: '处理告警失败',
  closeSuccess: '告警已关闭',
  closeError: '关闭告警失败',
  ruleNameRequired: '请输入规则名称',
  ruleNamePlaceholder: '例如：高温连续超限告警',
  descriptionPlaceholder: '补充适用范围、值班说明或排障提示',
  projectPlaceholder: '可按项目范围限定规则',
  productPlaceholder: '请选择产品',
  devicePlaceholder: '可选，用于限定到单台设备',
  metricPlaceholder: '请选择物模型属性或输入指标标识',
  metricRequired: '请选择指标或填写指标标识',
  levelRequired: '请选择告警级别',
  conditionRequired: '请选择触发方式',
  thresholdPlaceholder: '例如：80',
  windowSizePlaceholder: '例如：1',
  consecutiveCountPlaceholder: '例如：3',
  customExprPlaceholder: '例如：payload.temperature > 50 && payload.humidity > 80',
  customExprRequired: '请输入自定义表达式',
  processRemarkPlaceholder: '请输入处理说明、工单号或值班记录',
  emptyScope: '全部范围',
  noMetricOptions: '暂无物模型属性',
  setupGuideTitle: '配置步骤',
  setupGuideDescription: '建议按“基本信息 -> 适用范围 -> 告警等级块 -> 通知编排”的顺序配置，页面会实时汇总规则摘要。',
  setupGuideBasic: '步骤 1 填基本信息',
  setupGuideBasicDesc: '先定义规则名称和背景说明，方便后续搜索、交接和值班排查。',
  setupGuideScope: '步骤 2 定范围',
  setupGuideScopeDesc: '优先选产品，再按需细化到项目或单台设备，减少指标手输。',
  setupGuideBlocks: '步骤 3 配等级块',
  setupGuideBlocksDesc: '每个等级块先选级别和触发语义，再维护条件，系统会自动汇总规则主级别。',
  setupGuideNotify: '步骤 4 配通知编排',
  setupGuideNotifyDesc: '选择通知方式、接收组和指定接收人，让告警触发后直接进入值班链路。',
  configuredGroupCount: '已配置等级块',
  configuredConditionCount: '已配置条件数',
  configuredNotifyMethodCount: '已选通知方式',
  basicCardTitle: '基本信息',
  scopeCardTitle: '适用范围与主级别',
  notifyCardTitle: '通知编排',
  stepChooseLevel: '步骤 1 选择告警级别',
  stepChooseTrigger: '步骤 2 选择触发语义',
  stepReviewStrategy: '步骤 3 明确触发策略',
  stepConfigureConditions: '步骤 4 配置条件',
  levelStepHint: '先确定这是紧急、告警还是通知级别，再决定块内条件如何组合。',
  strategyStepHint: '这里决定该等级块是“满足全部条件”才触发，还是用命中数量控制。',
  groupConditionHint: '同一个等级块里的条件共同服务于这一档告警等级，建议只放语义相关的一组条件。',
  metricSelectRecommended: '建议先选择产品',
  metricSelectRecommendedDesc: '选择产品后可直接从物模型属性中选指标，配置更直观，也更不容易填错。',
  conditionParameterTitle: '条件参数',
  conditionHintThreshold: '适合“温度 > 80”这类直接阈值告警。',
  conditionHintCompare: '适合“当前值比上一周期上涨 20%”这类趋势型告警。',
  conditionHintContinuous: '适合“连续多次命中阈值”后再触发，降低抖动误报。',
  conditionHintAccumulate: '适合统计窗口内求和、计数、累计值超限的场景。',
  conditionHintCustom: '仅在标准条件无法覆盖时使用，表达式会按结构化规则保存。',
  notificationMethod: '通知方式',
  notificationMethodRequired: '请选择至少一种通知方式',
  notificationMethodPlaceholder: '请选择通知方式',
  notificationMethodHint:
    '告警规则只选“方式”，具体邮件、短信、Webhook 等通道配置由系统运维统一维护；Webhook 会自动使用当前租户已启用的配置。',
  recipientGroup: '告警接收组',
  recipientGroupPlaceholder: '可选，优先选择已维护的接收组',
  recipientGroupHint: '适合值班组、项目组、区域负责人等稳定接收对象。',
  recipientUsers: '指定接收人',
  recipientUsersPlaceholder: '可选，补充本规则特定接收人',
  recipientUsersHint: '适合临时负责人、专项值守或只想额外通知某几个人的场景。',
  recipientRequired: '请至少选择一个告警接收组或指定接收人',
  notificationPreview: '通知摘要',
  noNotificationConfig: '当前未配置通知推送，规则触发后只会保留告警记录。',
  methodColumn: '通知方式',
  receiverColumn: '接收对象',
  createRecipientGroup: '新建接收组',
  editRecipientGroup: '编辑接收组',
  recipientGroupName: '接收组名称',
  recipientGroupNamePlaceholder: '例如：生产值班一组',
  recipientGroupNameRequired: '请输入接收组名称',
  recipientGroupDescriptionLabel: '接收组说明',
  recipientGroupDescriptionPlaceholder: '说明该接收组适用的项目、班次或职责',
  recipientGroupMembers: '组内成员',
  recipientGroupMembersPlaceholder: '请选择组内成员',
  recipientGroupMemberCount: '成员数量',
  recipientGroupMemberPreview: '成员预览',
  recipientGroupSearch: '搜索接收组名称',
  recipientGroupEmpty: '暂无告警接收组',
  loadRecipientGroupError: '加载告警接收组失败',
  createRecipientGroupSuccess: '告警接收组创建成功',
  createRecipientGroupError: '创建告警接收组失败',
  updateRecipientGroupSuccess: '告警接收组更新成功',
  updateRecipientGroupError: '更新告警接收组失败',
  deleteRecipientGroupTitle: '确认删除告警接收组',
  deleteRecipientGroupSuccess: '告警接收组已删除',
  deleteRecipientGroupError: '删除告警接收组失败',
  deleteRecipientGroupMessagePrefix: '确认删除告警接收组“',
  deleteRecipientGroupMessageSuffix: '”吗？',
  noSelectableUsers: '当前租户暂无可选用户',
} as const;

export const ALARM_LEVEL_LABELS: Record<string, string> = {
  CRITICAL: '紧急',
  WARNING: '告警',
  INFO: '通知',
};

export const ALARM_STATUS_LABELS: Record<string, string> = {
  TRIGGERED: ALARM_TEXT.triggered,
  CONFIRMED: ALARM_TEXT.confirmed,
  PROCESSED: ALARM_TEXT.processed,
  CLOSED: ALARM_TEXT.closed,
};
